# ~/.config/alacritty/alacritty.toml
[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.selection]
text = "#e0def4"
background = "#26233a"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#6e6a86"

[colors.bright]
black = "#191724"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[[colors.indexed_colors]]
index = 16
color = "#908caa"

[[colors.indexed_colors]]
index = 17
color = "#524f67"

[[colors.indexed_colors]]
index = 18
color = "#403d52"

[[colors.indexed_colors]]
index = 19
color = "#1f1d2e"

[[colors.indexed_colors]]
index = 20
color = "#c5c3ce"

[font]
size = 11

[font.normal]
family = "hack"
style = "Regular"

[font.bold]
family = "hack"
style = "Bold"

[font.italic]
family = "hack"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[scrolling]
history = 50_000

[window]
opacity = 1.0