;;; fontawesome-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fontawesome.el

(autoload 'fontawesome "fontawesome" "\
Return fontawesome code point

(fn FONT-NAME)" t)
(autoload 'helm-fontawesome "fontawesome" nil t)
(autoload 'counsel-fontawesome "fontawesome" nil t)
(register-definition-prefixes "fontawesome" '("fontawesome--"))


;;; Generated autoloads from fontawesome-data.el

(register-definition-prefixes "fontawesome-data" '("fontawesome-alist"))

;;; End of scraped data

(provide 'fontawesome-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fontawesome-autoloads.el ends here
