;;; format-sql-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from format-sql.el

(autoload 'format-sql-region "format-sql" "\
Uses the \"format-sql\" tool to reformat the current region." t)
(autoload 'format-sql-buffer "format-sql" "\
Uses the \"format-sql\" tool to reformat the current buffer." t)
(register-definition-prefixes "format-sql" '("format-sql-" "get-file-type"))

;;; End of scraped data

(provide 'format-sql-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; format-sql-autoloads.el ends here
